# Generated by Django 4.1.1 on 2022-10-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_subject", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_email", models.CharField(max_length=200)),
                ("contact_message", models.CharField(max_length=1000)),
            ],
        ),
    ]
