# Generated by Django 4.1.1 on 2022-10-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findyourpalapp", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile_pictures/profilepic.png", upload_to="profile_pictures"
            ),
        ),
    ]
