# Generated by Django 4.1.1 on 2022-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findyourpalapp", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_yourself",
            field=models.CharField(default="I am an awesome person", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="age",
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(default="sanch@gmail.com", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                default="female",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(default="english", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(default="san", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="nationality",
            field=models.CharField(default="singaporean", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="pal_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                default="female",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="pal_nationality",
            field=models.CharField(
                choices=[(True, "Yes"), (False, "No")], default="anything", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="socialmedia",
            field=models.CharField(default="nothing", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="travel_itinerary",
            field=models.CharField(default="na", max_length=1000),
            preserve_default=False,
        ),
    ]
