# Generated by Django 4.0.3 on 2022-09-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=200)),
                ('story_desc', models.CharField(max_length=2000)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
    ]
