# Generated by Django 4.0.3 on 2022-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_image',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/169/169503.png', max_length=500),
        ),
    ]
