# Generated by Django 4.1.1 on 2022-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_story_story_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=200)),
                (
                    "profile_gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=1,
                    ),
                ),
                ("profile_age", models.IntegerField()),
                ("travel_destination", models.CharField(max_length=1000)),
            ],
        ),
    ]
