# Generated by Django 4.1.1 on 2022-09-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_rename_travel_destination_profile_travel_itinerary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="profile_age", new_name="age",
        ),
        migrations.RenameField(
            model_name="profile", old_name="profile_gender", new_name="gender",
        ),
        migrations.RenameField(
            model_name="profile", old_name="profile_name", new_name="name",
        ),
    ]
