# Generated by Django 4.1.1 on 2022-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_profile_age_profile_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="socialmedia",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
