# Generated by Django 4.1.1 on 2022-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_profile_email_profile_socialmedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_yourself",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
