# Generated by Django 4.1.1 on 2022-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_profile_about_yourself"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="language",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="nationality",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="pal_gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="pal_nationality",
            field=models.CharField(
                choices=[(True, "Yes"), (False, "No")], default=1, max_length=1
            ),
            preserve_default=False,
        ),
    ]
