# Generated by Django 4.1.1 on 2022-10-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_profile_language_profile_nationality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="story_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
