# Generated by Django 4.1.1 on 2022-10-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_contactus_contact_subject"),
    ]

    operations = [
        migrations.DeleteModel(name="contactus",),
    ]
