# Generated by Django 4.1.1 on 2022-12-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("findyourpalapp", "0003_alter_profile_image"),
        ("home", "0012_delete_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="story_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="findyourpalapp.profile",
            ),
            preserve_default=False,
        ),
    ]
