# Generated by Django 4.1.1 on 2022-12-21 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0013_story_story_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="story", name="story_user",),
        migrations.AddField(
            model_name="story",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
