# Generated by Django 4.1.1 on 2022-12-21 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_remove_story_story_user_story_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="story", name="user",),
        migrations.AddField(
            model_name="story",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
