# Generated by Django 4.1.1 on 2022-12-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_remove_story_user_story_created_on"),
    ]

    operations = [
        migrations.RemoveField(model_name="story", name="created_on",),
    ]
