# Generated by Django 4.1.1 on 2022-12-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_story_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="story_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="story_images/"
            ),
        ),
    ]
