# Generated by Django 4.1.1 on 2022-12-25 05:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_alter_story_story_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="country",
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="story",
            name="story_image",
            field=models.ImageField(
                blank=True,
                default="story_images/default.jpg",
                null=True,
                upload_to="story_images/",
            ),
        ),
    ]
