# Generated by Django 4.1.1 on 2022-12-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_alter_story_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="story", old_name="country", new_name="story_country",
        ),
    ]
