# Generated by Django 4.1.1 on 2022-12-25 06:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_rename_country_story_story_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="story_country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
