# Generated by Django 4.1.1 on 2022-12-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_alter_story_story_country"),
    ]

    operations = [
        migrations.DeleteModel(name="profile",),
    ]
